/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package consultorio.gui;

import consultorio.controle.TelaPrincipalControlador;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConsulta = new javax.swing.JMenu();
        jMenuPrimeiroCadastro = new javax.swing.JMenuItem();
        jMenuCadastrado = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consultório Médico");

        jMenuConsulta.setText("Consulta");

        jMenuPrimeiroCadastro.setText("Primeira Cadastro");
        jMenuPrimeiroCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrimeiroCadastroActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuPrimeiroCadastro);

        jMenuCadastrado.setText("Cadastrado");
        jMenuCadastrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastradoActionPerformed(evt);
            }
        });
        jMenuConsulta.add(jMenuCadastrado);

        jMenuBar1.add(jMenuConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadastradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCadastradoActionPerformed

    private void jMenuPrimeiroCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrimeiroCadastroActionPerformed
        TelaPrincipalControlador controle = new TelaPrincipalControlador(evt);
        controle.exibeTelaNovoPaciente();
    }//GEN-LAST:event_jMenuPrimeiroCadastroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastrado;
    private javax.swing.JMenu jMenuConsulta;
    private javax.swing.JMenuItem jMenuPrimeiroCadastro;
    // End of variables declaration//GEN-END:variables

}
